name: CI-CD1
on:
  push:
    branches: [ "inhohwangg-/-socket_test" ]
  pull_request:
    branches: [ "inhohwangg-/-socket_test" ]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.REMOTE_IP_1 }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/socket_test/app.js
            # git config --global --add safe.directory /home/ubuntu/socket_test
            sudo git pull
            # sudo npm update =>
            sudo npm install
            sudo pm2 reload all
